[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 10_000
via_ir = true
fuzz.runs = 512
invariant.runs = 128
invariant.depth = 64

[fmt]
line_length = 120
tab_width = 4

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
